### ISSUE TITLE
PHP Fatal Error, failed to open dir : Permission Denied

### ISSUE THREAD

**Issue by zoladesigners** [ConnectThink/WP-SCSS#198]
I am working with my website host WPEngine as well to see if the error is on their end but when migrating a site from one install to another the destination site will have this error and the site and admin becomes inaccessible:

PHP Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/nas/content/live/stghwilliams/wp-content/themes/zblocks-child/scss/): failed to open dir: Permission denied in /nas/content/live/hahnahwilliams/wp-content/plugins/wp-scss/class/class-wp-scss.php:169\nStack trace:\n#0 /nas/content/live/hahnahwilliams/wp-content/plugins/wp-scss/class/class-wp-scss.php(169): RecursiveDirectoryIterator->__construct('/nas/content/li...')\n#1 /nas/content/live/hahnahwilliams/wp-content/plugins/wp-scss/wp-scss.php(191): Wp_Scss->needs_compiling()\n#2 /nas/content/live/hahnahwilliams/wp-includes/class-wp-hook.php(292): wp_scss_needs_compiling('')\n#3 /nas/content/live/hahnahwilliams/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)\n#4 /nas/content/live/hahnahwilliams/wp-includes/plugin.php(484): WP_Hook->do_action(Array)\n#5 /nas/content/live/hahnahwilliams/wp-settings.php(582): do_action('wp_loaded')\n#6 /nas/content/live/hahnahwilliams/wp-config.php(123): require_once('/nas/content/li...')\n#7 in /nas/content/live/hahnahwilliams/wp-content/plugins/wp-scss/class/class-wp-scss.php on line 169

**Comment by shadoath** [comment]
Looks like a permission issue on the directory of your scss folder.

**Comment by zoladesigners** [comment]
Reseting files permissions doesn't fix it, that was the only thing I could think to try

![Screen Shot 2021-06-16 at 9 25 14 AM](https://user-images.githubusercontent.com/31413351/122227326-c8838700-ce84-11eb-980a-119bdfe612e8.png)

**Comment by shadoath** [comment]
What are the permissions on the `scss` folder that your compiling into?
`nas/content/live/stghwilliams/wp-content/themes/zblocks-child/scss/`

**Comment by zoladesigners** [comment]
I just ran an update on permissions on that folder as well as the compile destination with no change, same error about permissions. I haven't had to troubleshoot an issue like this before so if there is any other info that is helpful let me know!

![Screen Shot 2021-06-16 at 1 11 42 PM](https://user-images.githubusercontent.com/31413351/122263690-bf0a1700-cea4-11eb-82c9-aa9faa8e9743.png)

**Comment by niaccurshi** [comment]
It looks like you're dealing across environments?

/nas/content/live/stghwilliams/wp-content/themes/zblocks-child/scss/
versus
/nas/content/live/hahnahwilliams/wp-content/plugins/wp-scss/class/class-wp-scss.php

I believe you'll need to replace stghwilliams with hahnahwilliams in your WP database. Hopefully WP Engine can help you with that if you aren't confident in updating your database options yourself. There is an option in your options table "wpscss_options" that can be edited but it is a serialised array and so if you aren't sure how to change the serialised array to stay properly formatted, definitely get WP Engine support involved!

**Comment by zoladesigners** [comment]
I was looking in the database for a different site that is having this issue after a migration but I don't see anything named wpscss_options if I look in the wp_options table. Is it inside of another option? Any help in finding it is appreciated.

**Comment by shadoath** [comment]
@zoladesigners It will be in the `wp_options` table column `option_name` value `wpscss_options`
<img width="923" alt="image" src="https://user-images.githubusercontent.com/1946020/123825543-389a0000-d8bc-11eb-8282-00ce021ee749.png">

Is your migration issue the same as outlined above?

**Comment by zoladesigners** [comment]
Thank you! That was very helpful, yes it's the same issue just on a different website install on WP Engine.

**Comment by Redwineshiraz69** [comment]
I have the same issue but I found out it has the problem has an issue with PHP 7.4. When I downgrade and keep it at the old version 2.1.6 it's all good... 2.3.0 has the issues. I am on SiteGround hosting and using the UltraFast settings. As long I don't update the plugin it's fine. So why does it lose it's Permission Issue on the update?

**Comment by kvangorden21** [comment]
I have the same issue as @zoladesigners (see issue [#215](https://github.com/ConnectThink/WP-SCSS/issues/215). Need a fix ASAP!
