### ISSUE TITLE
Version 3.0 Crashed my entire site

### ISSUE THREAD

**Issue by wagonmonster** [ConnectThink/WP-SCSS#238]
2022/11/17 23:47:22 [error] 131032#131032: *208666 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class 'ScssPhp\ScssPhp\Block\CallableBlock' not found in /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Parser.php:494
Stack trace:
#0 /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Parser.php(287): ScssPhp\ScssPhp\Parser->parseChunk()
#1 /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(5707): ScssPhp\ScssPhp\Parser->parse('// Bootstrap fu...')
#2 /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(2673): ScssPhp\ScssPhp\Compiler->importFile('/www/ovidnapava...', Object(ScssPhp\ScssPhp\Formatter\OutputBlock))
#3 /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(2885): ScssPhp\ScssPhp\Compiler->compileImport(Array, Object(ScssPhp\ScssPhp\Formatter\OutputBlock))
#4 /www/ovidnapavalley_267/public/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(2348): ScssPhp\ScssPhp\Compiler->compileChild(Array, Object(ScssPh" while reading response header from upstream, client: 67.180.119.64, server: ovidnapavalley.com, request: "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-ovidnapavalley.sock:", host: "ovidnapavalley.com:49233", referrer: "https://ovidnapavalley.com/wp-admin/plugin-install.php?s=wp-scss&tab=search&type=term"

**Comment by neilparnold** [comment]
Same error on a bunch of my sites.  Had to disable the plugin.

**Comment by wagonmonster** [comment]
I have literally used this plugin on at least 20 sites. I am madly trying to disable auto updates on all of them before all hell breaks loose.

PLEASE FIX THIS!

**Comment by andreasjr** [comment]
Came here to say the same thing. We have the plugin on about 77 sites, and it took down 4, so I'm deactivating it before it takes down the rest.

From what my colleague told me, having "always recompile" enabled before the update crashed it. Rolling back, disabling that option, and updating the plugin seemed to work.

**Comment by sylvainNascimento** [comment]
Same ! Crash on update !

**Comment by tomte2000** [comment]
@andreasjr -> that only works if you don't compile. as soon you compile a changed sass-file the error comes again.
only solution is to go back to last version…

**Comment by bene82** [comment]
I confirm that compiling (without check on automatic compiling) I get a fatal error.

**Comment by Quentin64600** [comment]
Same here, some websites crashed

**Comment by aduchenet** [comment]
It can be solved by replacing the embedded `scssphp` directory by the latest version of https://scssphp.github.io/scssphp/ .

**Comment by airplanenoise** [comment]
+1, we had to rollback https://wordpress.org/plugins/wp-rollback/ - hopefully this will be fixed by an emergency update as it does affect many sites for many people.

**Comment by foinf** [comment]
+1 It borked a live site that I know of and I am sure it crashed other sites that use as well and now I am having to go through all the other sites to find out. How did this happen? Never using this plugin again.

**Comment by rileeugenia** [comment]
+1
Crash on update !
@Fatal error: Uncaught Error: Class 'ScssPhp\ScssPhp\Block\MediaBlock' ... in /xxxxxxx/xxxx//wp-content/plugins/wp-scss/scssphp/src/Parser.php on line 477

**Comment by agkovalev** [comment]
+1 
Sites with autoupdate enabled crashed.

**Comment by howardperkins** [comment]
Here's a link to v2.4 for the time being: https://github.com/ConnectThink/WP-SCSS/archive/refs/tags/2.4.0.zip

If you have access to your site's filesystem then delete the old plugin folder at wp-content/plugins/wp-scss and replace it with the above, renaming the folder to wp-scss. Your site should return to normal until the devs provide a fixed update.

**Comment by dltownsend3** [comment]
Same issue here. Crashed 6 of my company's sites. Not sure I can trust this plugin again, as this shouldn't have even been possible in my mind, and it crashed the sites in such a way that a notice couldn't even be sent to the admin email. Had to hear about it from a client - the worst case scenario.

**Comment by wagonmonster** [comment]
I switched all my sites over to another SCSS Compiler plugin, I can't trust these guys anymore.

**Comment by foinf** [comment]
> I switched all my sites over to another SCSS Compiler plugin, I can't trust these guys anymore.

This was beyond painful and is still going on...I have to go through more than 80 sites where I have used it. I am still sifting through them one by one. The amount of stress this has created has never happened to me in 8 years. I can't believe this actually happened.

**Comment by foinf** [comment]
How long before the author atleast take the defective update offline so that more damage may be prevented?

Can wordpress be contacted to take the auto update offline?

**Comment by wagonmonster** [comment]
> > I switched all my sites over to another SCSS Compiler plugin, I can't trust these guys anymore.
> 
> This was beyond painful and is still going on...I have to go through more than 80 sites where I have used it. I am still sifting through them one by one. The amount of stress this has created has never happened to me in 8 years. I can't believe this actually happened.

I feel your pain, it's ridiculous this happened and it's infuriating that they haven't fixed it yet.

**Comment by foinf** [comment]
> 

I think such gross incompetence should be reason enough for WordPress to immediately delist this from its plugin library. I can't go through these sites fast enough and I fear many might be broken or about to break.

**Comment by airplanenoise** [comment]
i had had an issue in the past with this plugin and i mostly have it setup to _disable auto-updates_. i don't want to yell at the developer of this plugin, it's brought great productivity to our development flow. it's not a paid plugin. i think of it as a "sleepy plugin", i was actually surprised there was an update. we do rely on it quite a bit, but it's only an issue if you autoupdate, so let's learn from that. just curious @wagonmonster what is the compiler you use? hopefully this will be fixed soon. i just got an email from another developer saying that the latest update caused a fatal error — that at least is helpful: if there is a way for the owner of the plugin to send a message to all people that installed it that might help!

**Comment by dltownsend3** [comment]
> 

I had the compiled stylesheet link hardcoded so I was able to bring my sites back up by just renaming the plugin folder to disable it, might work for you or anyone else who set their sites up that way.

**Comment by foinf** [comment]
> 

I know and that's what I am doing but there are many sites. Also imagine the plight of someone who has to check up on even more sites like more than 150+. This is nothing short of absolute nightmare.

**Comment by KustomKode** [comment]
THIS IS A SUPER SIMPLE FIX

Although it shouldn't have been released before being tested for quality assurance, accidents happen, luckily as a developer who has had many accidents in my career, I have become pretty good at troubleshooting.

The simplest fix is to FTP into your site and go to the "scss" plugin folder, open it and delete the entire folder named "scssphp" and replace it with a new folder of the same name and put the files from https://github.com/scssphp/scssphp/ inside of it. It takes less than 60 seconds to fix.

**Comment by lakuapik** [comment]
**What i found is:** for some reason, the version that wordpress plugin downloaded does not contain the [`scssphp/src/Block`](https://github.com/ConnectThink/WP-SCSS/tree/master/scssphp/src/Block) directory, which is i believe required to compile the scss.

**From wordpress plugin**

<img width="699" alt="image" src="https://user-images.githubusercontent.com/20186786/202831163-c9b5ee82-8417-4817-94e9-f7262a7c8753.png">

**From [github release]()**

<img width="397" alt="image" src="https://user-images.githubusercontent.com/20186786/202831225-abe72d7b-207b-4c5c-b043-c6424e5fb544.png">

so i dont think its the developer to blame but how the plugin delivery is. #cmmiw

**Comment by lakuapik** [comment]
if you still want to use the version 3.0.0, the hotfix is you need to upload the  [`scssphp/src/Block`](https://github.com/ConnectThink/WP-SCSS/tree/master/scssphp/src/Block) directory to your `wp-scss` plugin. I've tried and it works.

before:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/20186786/202832126-6f546e91-ad8c-441a-a301-7e8753244c28.png">

after:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/20186786/202832131-c836b59a-4e32-4a78-90c4-641b243d85e6.png">

**Comment by bene82** [comment]
Ok. So we can close the issue downloading the plugin from Github and not updating with WordPress.

**Comment by wagonmonster** [comment]
> Ok. So we can close the issue downloading the plugin from Github and not updating with WordPress.

It's still broken, so no, don't close it.

**Comment by foinf** [comment]
> > Ok. So we can close the issue downloading the plugin from Github and not updating with WordPress.
> 
> It's still broken, so no, don't close it.

The problem update is still out there breaking sites. Just happened to me a couple of hours ago, thankfully, on a staging site. Is there no way of taking it offline?

**Comment by agkovalev** [comment]
Just add folder Block to scssphp folder. You can find it on github

**Comment by arekuki** [comment]
+1

**Comment by nbaudet** [comment]
I did a PR that I mention in [this issue](https://github.com/ConnectThink/WP-SCSS/issues/239#issuecomment-1349194887).

**Comment by shadoath** [comment]
So sorry for this long wait to fix this issue. I only receive notifications with direct @shadoath mentions.

I mistakenly missed some files when committing to WordPress SVN for version 3.0.0 (Wish wish wish they used git and tags for versioning)
 
This is now fixed in version 4.0.2. Which also requires PHP 7.2

I also pushed version 3.0.2 with a fix for just that major version and the missing files.

If you would like to help maintain this plugin, please reach out [here](https://github.com/ConnectThink/WP-SCSS/issues/242).

**Comment by shadoath** [comment]
There are a lot of comments here complaining. When I read this it is like seeing a little kid in a tantrum. Sorry for the inconvenience and trouble.

Then there are some who took action and found how to fix this issue and then offered it up to others. Bravo!

I was happy to find this comment:
>... i don't want to yell at the developer of this plugin, it's brought great productivity to our development flow. it's not a paid plugin. i think of it as a "sleepy plugin", i was actually surprised there was an update. we do rely on it quite a bit, but it's only an issue if you autoupdate, so let's learn from that....]

Thank you for giving your insight in calm and collected way.  I pushed it out as v3.0.0 thinking it would require a manual update as it was a major version change and would not cause so many issues from auto-updating, I was wrong.

> hopefully this will be fixed soon. i just got an email from another developer saying that the latest update caused a fatal error — that at least is helpful: if there is a way for the owner of the plugin to send a message to all people that installed it that might help!

This is helpful! I'll look into the email option I didn't know that a plugin author could do that. I'm only a maintainer so I'll have to see if I have that option on WordPress.

My last update was a rush and dealing with SVN is not as smooth as with Git, which lead me to miss a few files and caused this blowup. I updated my website and moved on not realizing this issue shows as soon as a new compile tries to run.

As I noted above I think having another maintainer who is active with this plugin would be a big help for stability and adding features.
