### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by leepeterson** [ConnectThink/WP-SCSS#72]
I've started to write this issue report 6 times now in 4 days, but every time I do, I think of some other test I can run to ensure it's just me and that I'm not wasting anyone's time. So, now that that's been said... 

This issue began after I ran WP-CLI's doctor check on a newly-launched website. WP-SCSS plugin version 1.2.2 and 1.2.1. Haven't had time to check other versions.

```
$ wp doctor check --all
Running checks  76 % [==================================================================================================================================>                                      ] 0:03 / 0:05PHP Fatal error:  Uncaught Error: Call to a member function needs_compiling() on null in /srv/users/REDACTED/apps/production/public/wp-content/plugins/wp-scss/wp-scss.php:167
Stack trace:
#0 /srv/users/REDACTED/apps/production/public/wp-includes/class-wp-hook.php(298): wp_scss_needs_compiling('')
#1 /srv/users/REDACTED/apps/production/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /srv/users/REDACTED/apps/production/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /srv/users/REDACTED/apps/production/public/wp-includes/general-template.php(2574): do_action('wp_head')
#4 /srv/users/REDACTED/apps/production/public/wp-content/themes/REDACTED/header.php(14): wp_head()
#5 /srv/users/REDACTED/apps/production/public/wp-includes/template.php(684): require_once('/srv/users/serv...')
#6 /srv/users/REDACTED/apps/production/public/wp-includes/template.php(643): load_template('/srv/users/serv...', true)
#7 /srv/users/REDACTED/apps/production/public/wp-includes/genera in /srv/users/REDACTED/apps/production/public/wp-content/plugins/wp-scss/wp-scss.php on line 167
Fatal error: Uncaught Error: Call to a member function needs_compiling() on null in /srv/users/REDACTED/apps/production/public/wp-content/plugins/wp-scss/wp-scss.php:167
Stack trace:
#0 /srv/users/REDACTED/apps/production/public/wp-includes/class-wp-hook.php(298): wp_scss_needs_compiling('')
#1 /srv/users/REDACTED/apps/production/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /srv/users/REDACTED/apps/production/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /srv/users/REDACTED/apps/production/public/wp-includes/general-template.php(2574): do_action('wp_head')
#4 /srv/users/REDACTED/apps/production/public/wp-content/themes/REDACTED/header.php(14): wp_head()
#5 /srv/users/REDACTED/apps/production/public/wp-includes/template.php(684): require_once('/srv/users/serv...')
#6 /srv/users/REDACTED/apps/production/public/wp-includes/template.php(643): load_template('/srv/users/serv...', true)
#7 /srv/users/REDACTED/apps/production/public/wp-includes/genera in /srv/users/REDACTED/apps/production/public/wp-content/plugins/wp-scss/wp-scss.php on line 167
<!DOCTYPE html>

[OTHER HEAD OUTPUT HERE]

<link rel="alternate" type="text/xml+oembed" href="https://www.REDACTED.com/wp-api/oembed/1.0/embed?url=https%3A%2F%2Fwww.REDACTED.com%2F&#038;format=xml" />
[DOCTOR CHECK ENDS ABRUPTLY HERE]
```

Here's the output from `wp_head()`...

```
WP_Hook Object
(
    [callbacks] => Array
        (
            [1] => Array
                (
                    [_wp_render_title_tag] => Array
                        (
                            [function] => _wp_render_title_tag
                            [accepted_args] => 1
                        )

                    [wp_enqueue_scripts] => Array
                        (
                            [function] => wp_enqueue_scripts
                            [accepted_args] => 1
                        )

                    [noindex] => Array
                        (
                            [function] => noindex
                            [accepted_args] => 1
                        )

                    [wp_post_preview_js] => Array
                        (
                            [function] => wp_post_preview_js
                            [accepted_args] => 1
                        )

                    [eventorganiser_cgmp_workaround] => Array
                        (
                            [function] => eventorganiser_cgmp_workaround
                            [accepted_args] => 1
                        )

                )

            [2] => Array
                (
                    [wp_resource_hints] => Array
                        (
                            [function] => wp_resource_hints
                            [accepted_args] => 1
                        )

                )

            [8] => Array
                (
                    [wp_print_styles] => Array
                        (
                            [function] => wp_print_styles
                            [accepted_args] => 1
                        )

                )

            [9] => Array
                (
                    [wp_print_head_scripts] => Array
                        (
                            [function] => wp_print_head_scripts
                            [accepted_args] => 1
                        )

                )

            [10] => Array
                (
                    [adjacent_posts_rel_link_wp_head] => Array
                        (
                            [function] => adjacent_posts_rel_link_wp_head
                            [accepted_args] => 0
                        )

                    [locale_stylesheet] => Array
                        (
                            [function] => locale_stylesheet
                            [accepted_args] => 1
                        )

                    [rel_canonical] => Array
                        (
                            [function] => rel_canonical
                            [accepted_args] => 1
                        )

                    [wp_shortlink_wp_head] => Array
                        (
                            [function] => wp_shortlink_wp_head
                            [accepted_args] => 0
                        )

                    [_custom_logo_header_styles] => Array
                        (
                            [function] => _custom_logo_header_styles
                            [accepted_args] => 1
                        )

                    [wp_oembed_add_discovery_links] => Array
                        (
                            [function] => wp_oembed_add_discovery_links
                            [accepted_args] => 1
                        )

                    [wp_oembed_add_host_js] => Array
                        (
                            [function] => wp_oembed_add_host_js
                            [accepted_args] => 1
                        )

                    [wp_scss_needs_compiling] => Array
                        (
                            [function] => wp_scss_needs_compiling
                            [accepted_args] => 1
                        )

                    [GFForms::load_admin_bar_styles] => Array
                        (
                            [function] => Array
                                (
                                    [0] => GFForms
                                    [1] => load_admin_bar_styles
                                )

                            [accepted_args] => 1
                        )

                    [wp_admin_bar_header] => Array
                        (
                            [function] => wp_admin_bar_header
                            [accepted_args] => 1
                        )

                    [_admin_bar_bump_cb] => Array
                        (
                            [function] => _admin_bar_bump_cb
                            [accepted_args] => 1
                        )

                )

            [99] => Array
                (
                    [wp_site_icon] => Array
                        (
                            [function] => wp_site_icon
                            [accepted_args] => 1
                        )

                )

            [101] => Array
                (
                    [wp_custom_css_cb] => Array
                        (
                            [function] => wp_custom_css_cb
                            [accepted_args] => 1
                        )

                )

        )

    [iterations:WP_Hook:private] => Array
        (
        )

    [current_priority:WP_Hook:private] => Array
        (
        )

    [nesting_level:WP_Hook:private] => 0
    [doing_action:WP_Hook:private] => 
)
```

My guess is an argument isn't being passed. Plugin works fine, BTW. That makes it even more baffling.

**Comment by brrn** [comment]
I'm not familiar with WP-CLI's doctor check. Is there another way to replicate this issue?
